/*
 * RAF_avr_regs_generated.h — AUTO-GENERATED by scripts/gen_avr_regs.py
 * Source: ATmega328P datasheet Atmel 8271D, I/O Memory Map.
 * DO NOT EDIT MANUALLY — regenerate via: python3 scripts/gen_avr_regs.py
 *
 * Checksum (CRC-32 of name=ADDR pairs sorted by address): 0x5A9F075B
 * Validate: python3 scripts/gen_avr_regs.py --check
 */

#ifndef RAF_AVR_REGS_GENERATED_H
#define RAF_AVR_REGS_GENERATED_H

#include <stdint.h>

/* Validation token — matches CRC-32 computed by gen_avr_regs.py */
#define RAF_AVR_REGS_CHECKSUM 0x5A9F075BUL

/* All addresses are ATmega328P I/O memory map offsets (data space). */
/* Access via RAFA_MMIO8(addr) macro from RAF_rafaelia_common.h.    */

#define AVR_PINB             0x23U  /* Port B Input Pins */
#define AVR_DDRB             0x24U  /* Port B Data Direction Register */
#define AVR_PORTB            0x25U  /* Port B Data Register */
#define AVR_PINC             0x26U  /* Port C Input Pins */
#define AVR_DDRC             0x27U  /* Port C Data Direction Register */
#define AVR_PORTC            0x28U  /* Port C Data Register */
#define AVR_PIND             0x29U  /* Port D Input Pins */
#define AVR_DDRD             0x2AU  /* Port D Data Direction Register */
#define AVR_PORTD            0x2BU  /* Port D Data Register */
#define AVR_SPCR             0x4CU  /* SPI Control Register */
#define AVR_SPSR             0x4DU  /* SPI Status Register */
#define AVR_SPDR             0x4EU  /* SPI Data Register */
#define AVR_SMCR             0x53U  /* Sleep Mode Control Register */
#define AVR_MCUSR            0x54U  /* MCU Status Register (BORF/EXTRF/PORF/WDRF) */
#define AVR_WDTCSR           0x60U  /* Watchdog Timer Control Register */
#define AVR_TIMSK1           0x6FU  /* Timer/Counter1 Interrupt Mask Register */
#define AVR_ADCL             0x78U  /* ADC Data Register Low */
#define AVR_ADCH             0x79U  /* ADC Data Register High */
#define AVR_ADCSRA           0x7AU  /* ADC Control and Status Register A */
#define AVR_ADCSRB           0x7BU  /* ADC Control and Status Register B */
#define AVR_ADMUX            0x7CU  /* ADC Multiplexer Selection Register */
#define AVR_TCCR1A           0x80U  /* Timer/Counter1 Control Register A */
#define AVR_TCCR1B           0x81U  /* Timer/Counter1 Control Register B */
#define AVR_TCCR1C           0x82U  /* Timer/Counter1 Control Register C */
#define AVR_TCNT1L           0x84U  /* Timer/Counter1 Low Byte */
#define AVR_TCNT1H           0x85U  /* Timer/Counter1 High Byte */
#define AVR_ICR1L            0x86U  /* Input Capture Register 1 Low */
#define AVR_ICR1H            0x87U  /* Input Capture Register 1 High */
#define AVR_OCR1AL           0x88U  /* Output Compare Register 1A Low */
#define AVR_OCR1AH           0x89U  /* Output Compare Register 1A High */
#define AVR_OCR1BL           0x8AU  /* Output Compare Register 1B Low */
#define AVR_OCR1BH           0x8BU  /* Output Compare Register 1B High */
#define AVR_UCSR0A           0xC0U  /* USART0 Control and Status Register A */
#define AVR_UCSR0B           0xC1U  /* USART0 Control and Status Register B */
#define AVR_UCSR0C           0xC2U  /* USART0 Control and Status Register C */
#define AVR_UBRR0L           0xC4U  /* USART0 Baud Rate Register Low */
#define AVR_UBRR0H           0xC5U  /* USART0 Baud Rate Register High */
#define AVR_UDR0             0xC6U  /* USART0 I/O Data Register */
#define AVR_TWBR             0xB8U  /* TWI Bit Rate Register */
#define AVR_TWSR             0xB9U  /* TWI Status Register */
#define AVR_TWAR             0xBAU  /* TWI (Slave) Address Register */
#define AVR_TWDR             0xBBU  /* TWI Data Register */
#define AVR_TWCR             0xBCU  /* TWI Control Register */
#define AVR_TWAMR            0xBDU  /* TWI (Slave) Address Mask Register */

#endif /* RAF_AVR_REGS_GENERATED_H */
