#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "patch_apkc_runtime_source", ROOT / "scripts/patch_apkc_runtime_source.py"
)
assert SPEC and SPEC.loader
PATCHER = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = PATCHER
SPEC.loader.exec_module(PATCHER)


class ApkCRuntimeSourceHardeningTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.source = (ROOT / "Apkc/apkc.c").read_text(encoding="utf-8")

    def test_transform_applies_all_contract_changes(self) -> None:
        generated, changes = PATCHER.transform(self.source)
        self.assertEqual(len(changes), 13)
        self.assertTrue(generated.startswith("/* GENERATED by"))

        required = [
            "compiler output exceeds bounded buffer",
            "source exceeds 1MiB bounded input",
            "_apkc_is_dex",
            "_apkc_is_elf64_aarch64",
            "so64_buf_ptr = _fork_out",
            "dex_output profile requires D8",
            "waited!=pid",
            "_apkc_sc5_32",
            'static const char _tmpout_so[]  = ".apkc-out.so"',
            'd8args[nd++] = "."',
        ]
        for marker in required:
            self.assertIn(marker, generated)

        forbidden = [
            '"/tmp/apkc_out.so"',
            '"/tmp/jsx_out.js"',
            '"/tmp/classes.dex"',
            '"/tmp/apkc_compute.spv"',
            '"/tmp/apkc_dsp.so"',
            "fork_exec_wait: not supported on ARM32",
            "outsz < sizeof(_so64_buf) ? outsz : sizeof(_so64_buf)",
            "outsz < sizeof(_dex_buf) ? outsz : sizeof(_dex_buf)",
        ]
        for marker in forbidden:
            self.assertNotIn(marker, generated)

    def test_transform_is_byte_deterministic(self) -> None:
        first, first_changes = PATCHER.transform(self.source)
        second, second_changes = PATCHER.transform(self.source)
        self.assertEqual(first, second)
        self.assertEqual(first_changes, second_changes)
        self.assertEqual(
            PATCHER.sha256_bytes(first.encode("utf-8")),
            PATCHER.sha256_bytes(second.encode("utf-8")),
        )

    def test_anchor_drift_is_fail_closed(self) -> None:
        drifted = self.source.replace(
            "static u8 _fork_out[0x100000]; /* fork+exec output buffer */",
            "static u8 _fork_out[0x200000]; /* changed outside hardening contract */",
            1,
        )
        with self.assertRaisesRegex(ValueError, "APKC-RH-001"):
            PATCHER.transform(drifted)

    def test_every_change_id_is_unique(self) -> None:
        ids = [item.change_id for item, _, _ in PATCHER.TRANSFORMS]
        self.assertEqual(len(ids), len(set(ids)))
        self.assertEqual(ids, [f"APKC-RH-{index:03d}" for index in range(1, 14)])


if __name__ == "__main__":
    unittest.main()
