#!/bin/sh
# Build a minimal NativeActivity APK on-device, without Gradle, Android SDK,
# Android Studio, Maven, or a network connection.  The output is intentionally
# limited to ApkC's internal-assembly route.
# Contract: docs/APKC_HERMETIC_TERMUX.md
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
APKC_DIR="$ROOT/Apkc"

OUT_DIR="$ROOT/build/apkc-hermetic"
SOURCE="$APKC_DIR/hello.s.txt"
PACKAGE_NAME="com.rafaelia.polimata.hermetic"
APP_LABEL="RafPolimata Hermetic"
LIB_NAME="rafpolimata_hermetic"
ABI="both"
MIN_SDK="24"
TARGET_SDK="35"
SIGN=0
CC_BIN="${APKC_CC:-cc}"

usage() {
    cat <<'EOF'
Usage:
  sh scripts/apkc_termux_hermetic_build.sh [options]

Builds a minimal ApkC NativeActivity APK locally. It never downloads,
installs packages, calls Gradle, or resolves Maven dependencies.

Options:
  --source FILE             internal-assembly source (default: Apkc/hello.s.txt)
  --out DIR                 output directory (default: build/apkc-hermetic)
  --package NAME            Android package name
  --label TEXT              Android application label
  --lib NAME                native library basename (letters/digits/_ only)
  --abi both|armeabi-v7a|arm64-v8a
  --min-sdk N               minSdkVersion (default: 24)
  --target-sdk N            targetSdkVersion (default: 35)
  --sign                    sign with local apksigner and an existing keystore
  --unsigned                do not sign (default)
  --help                    show this help

Signing variables (only with --sign; never stored by this script):
  APKSIGNER_KEYSTORE        existing local keystore path
  APKSIGNER_ALIAS           existing key alias
  APKSIGNER_KS_PASS_FILE    file containing the keystore password
  APKSIGNER_KEY_PASS_FILE   optional file containing the key password

Host requirement: a local C compiler available as ${APKC_CC:-cc}.
The APK payload itself is generated by ApkC without Gradle/SDK/JDK/aapt/d8.
EOF
}

die() {
    printf 'apkc-hermetic: ERROR: %s\n' "$*" >&2
    exit 1
}

need_value() {
    [ "$#" -ge 2 ] || die "missing value for $1"
}

sha256_or_token() {
    if command -v sha256sum >/dev/null 2>&1; then
        # Output files are created by this script and do not contain whitespace.
        set -- $(sha256sum "$1")
        printf '%s\n' "$1"
    else
        printf '%s\n' 'TOKEN_VAZIO_SHA256SUM_ABSENT'
    fi
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --source) need_value "$@"; SOURCE=$2; shift 2 ;;
        --out) need_value "$@"; OUT_DIR=$2; shift 2 ;;
        --package) need_value "$@"; PACKAGE_NAME=$2; shift 2 ;;
        --label) need_value "$@"; APP_LABEL=$2; shift 2 ;;
        --lib) need_value "$@"; LIB_NAME=$2; shift 2 ;;
        --abi) need_value "$@"; ABI=$2; shift 2 ;;
        --min-sdk) need_value "$@"; MIN_SDK=$2; shift 2 ;;
        --target-sdk) need_value "$@"; TARGET_SDK=$2; shift 2 ;;
        --sign) SIGN=1; shift ;;
        --unsigned) SIGN=0; shift ;;
        --help|-h) usage; exit 0 ;;
        *) die "unknown option: $1" ;;
    esac
done

case "$ABI" in
    both) ABI_FLAG=-both ;;
    armeabi-v7a) ABI_FLAG=-32 ;;
    arm64-v8a) ABI_FLAG=-64 ;;
    *) die "--abi must be both, armeabi-v7a, or arm64-v8a" ;;
esac

case "$PACKAGE_NAME" in
    ''|.*|*.) die "invalid Android package name" ;;
    *[!A-Za-z0-9._]*) die "package name may only contain letters, digits, . and _" ;;
esac
case "$LIB_NAME" in
    ''|*[!A-Za-z0-9_]*) die "--lib may only contain letters, digits and _" ;;
esac
case "$MIN_SDK" in ''|*[!0-9]*) die "--min-sdk must be numeric" ;; esac
case "$TARGET_SDK" in ''|*[!0-9]*) die "--target-sdk must be numeric" ;; esac

[ -f "$APKC_DIR/apkc.c" ] || die "missing $APKC_DIR/apkc.c"
[ -f "$SOURCE" ] || die "missing source: $SOURCE"
command -v "$CC_BIN" >/dev/null 2>&1 || die "local C compiler not found: $CC_BIN"

mkdir -p "$OUT_DIR"
BUILD_LOG="$OUT_DIR/build.log"
BIN_TMP="$OUT_DIR/apkc-host.tmp.$$"
BIN="$OUT_DIR/apkc-host"
UNSIGNED_TMP="$OUT_DIR/${LIB_NAME}-unsigned.apk.tmp.$$"
UNSIGNED="$OUT_DIR/${LIB_NAME}-unsigned.apk"
SIGNED_TMP="$OUT_DIR/${LIB_NAME}-signed.apk.tmp.$$"
SIGNED="$OUT_DIR/${LIB_NAME}-signed.apk"
RECEIPT="$OUT_DIR/receipt.env"

{
    printf '%s\n' '# ApkC hermetic build log'
    printf 'mode=%s\n' 'APKC_INTERNAL_ASM'
    printf 'date_utc=%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf 'compiler=%s\n' "$CC_BIN"
    printf '%s\n' 'command=cc -std=c11 -Oz -Wno-unused-function -nostartfiles -Wl,-e,_start Apkc/apkc.c'
    "$CC_BIN" -std=c11 -Oz -Wno-unused-function -nostartfiles -Wl,-e,_start \
        "$APKC_DIR/apkc.c" -o "$BIN_TMP"
} >"$BUILD_LOG" 2>&1 || die "ApkC bootstrap compilation failed; inspect $BUILD_LOG"

[ -x "$BIN_TMP" ] || die "compiler exited successfully but did not produce executable ApkC"
mv -f "$BIN_TMP" "$BIN"

{
    printf 'command=%s\n' "$BIN $SOURCE -o $UNSIGNED_TMP -p $PACKAGE_NAME -l $APP_LABEL -n $LIB_NAME -m $MIN_SDK -t $TARGET_SDK $ABI_FLAG"
    "$BIN" "$SOURCE" -o "$UNSIGNED_TMP" -p "$PACKAGE_NAME" -l "$APP_LABEL" \
        -n "$LIB_NAME" -m "$MIN_SDK" -t "$TARGET_SDK" "$ABI_FLAG"
} >>"$BUILD_LOG" 2>&1 || die "ApkC did not generate an APK; inspect $BUILD_LOG"

[ -s "$UNSIGNED_TMP" ] || die "ApkC returned success without a non-empty APK"
mv -f "$UNSIGNED_TMP" "$UNSIGNED"

SIGNING_STATE=UNSIGNED
if [ "$SIGN" -eq 1 ]; then
    : "${APKSIGNER_KEYSTORE:?set APKSIGNER_KEYSTORE for --sign}"
    : "${APKSIGNER_ALIAS:?set APKSIGNER_ALIAS for --sign}"
    : "${APKSIGNER_KS_PASS_FILE:?set APKSIGNER_KS_PASS_FILE for --sign}"
    [ -f "$APKSIGNER_KEYSTORE" ] || die "keystore not found: $APKSIGNER_KEYSTORE"
    [ -f "$APKSIGNER_KS_PASS_FILE" ] || die "keystore password file not found"
    command -v apksigner >/dev/null 2>&1 || die "--sign requires local apksigner"

    if [ -n "${APKSIGNER_KEY_PASS_FILE:-}" ]; then
        [ -f "$APKSIGNER_KEY_PASS_FILE" ] || die "key password file not found"
        apksigner sign --ks "$APKSIGNER_KEYSTORE" --ks-key-alias "$APKSIGNER_ALIAS" \
            --ks-pass "file:$APKSIGNER_KS_PASS_FILE" --key-pass "file:$APKSIGNER_KEY_PASS_FILE" \
            --min-sdk-version "$MIN_SDK" --out "$SIGNED_TMP" "$UNSIGNED" >>"$BUILD_LOG" 2>&1
    else
        apksigner sign --ks "$APKSIGNER_KEYSTORE" --ks-key-alias "$APKSIGNER_ALIAS" \
            --ks-pass "file:$APKSIGNER_KS_PASS_FILE" --min-sdk-version "$MIN_SDK" \
            --out "$SIGNED_TMP" "$UNSIGNED" >>"$BUILD_LOG" 2>&1
    fi
    [ -s "$SIGNED_TMP" ] || die "apksigner returned without a signed APK"
    apksigner verify --verbose --print-certs "$SIGNED_TMP" >>"$BUILD_LOG" 2>&1 || \
        die "apksigner verification failed; inspect $BUILD_LOG"
    mv -f "$SIGNED_TMP" "$SIGNED"
    SIGNING_STATE=SIGNED_AND_VERIFIED
fi

{
    printf 'schema=%s\n' 'raf.apkc.hermetic-build.v1'
    printf 'state=%s\n' 'BUILD_CREATED'
    printf 'claim_allowed=%s\n' 'false'
    printf 'mode=%s\n' 'APKC_INTERNAL_ASM'
    printf 'network=%s\n' 'NOT_USED'
    printf 'gradle=%s\n' 'NOT_USED'
    printf 'android_sdk=%s\n' 'NOT_USED'
    printf 'jvm_d8_aapt=%s\n' 'NOT_USED'
    printf 'source=%s\n' "$SOURCE"
    printf 'source_sha256=%s\n' "$(sha256_or_token "$SOURCE")"
    printf 'apkc_host_sha256=%s\n' "$(sha256_or_token "$BIN")"
    printf 'unsigned_apk=%s\n' "$UNSIGNED"
    printf 'unsigned_apk_sha256=%s\n' "$(sha256_or_token "$UNSIGNED")"
    printf 'requested_abi=%s\n' "$ABI"
    printf 'package=%s\n' "$PACKAGE_NAME"
    printf 'min_sdk=%s\n' "$MIN_SDK"
    printf 'target_sdk=%s\n' "$TARGET_SDK"
    printf 'signing=%s\n' "$SIGNING_STATE"
    if [ "$SIGNING_STATE" = SIGNED_AND_VERIFIED ]; then
        printf 'signed_apk=%s\n' "$SIGNED"
        printf 'signed_apk_sha256=%s\n' "$(sha256_or_token "$SIGNED")"
    fi
    printf 'structural_validation=%s\n' 'TOKEN_VAZIO'
    printf 'install_and_runtime=%s\n' 'TOKEN_VAZIO'
    printf '%s\n' 'scope=Minimal NativeActivity via ApkC internal assembly; not a replacement for Gradle/Kotlin/Compose builds.'
} >"$RECEIPT"

printf 'apkc-hermetic: unsigned APK: %s\n' "$UNSIGNED"
if [ "$SIGNING_STATE" = SIGNED_AND_VERIFIED ]; then
    printf 'apkc-hermetic: signed APK:   %s\n' "$SIGNED"
fi
printf 'apkc-hermetic: receipt:      %s\n' "$RECEIPT"
