#!/usr/bin/env python3
"""
S04 — Gerador de header validado para registradores ATmega328P.

Gera RAF_avr_regs_generated.h com endereços reais da datasheet ATmega328P
(Atmel doc 8271, rev D, tabela de I/O memory map).
Inclui checksum CRC-32 dos valores gerados para detecção de edição manual.
"""

import sys
import zlib

# Endereços baseados na datasheet ATmega328P (Atmel 8271D) — Memory Map I/O
REGISTERS = [
    # (name, address, description)
    # GPIO Port B
    ("AVR_PINB",    0x23, "Port B Input Pins"),
    ("AVR_DDRB",    0x24, "Port B Data Direction Register"),
    ("AVR_PORTB",   0x25, "Port B Data Register"),
    # GPIO Port C
    ("AVR_PINC",    0x26, "Port C Input Pins"),
    ("AVR_DDRC",    0x27, "Port C Data Direction Register"),
    ("AVR_PORTC",   0x28, "Port C Data Register"),
    # GPIO Port D
    ("AVR_PIND",    0x29, "Port D Input Pins"),
    ("AVR_DDRD",    0x2A, "Port D Data Direction Register"),
    ("AVR_PORTD",   0x2B, "Port D Data Register"),
    # SPI
    ("AVR_SPCR",    0x4C, "SPI Control Register"),
    ("AVR_SPSR",    0x4D, "SPI Status Register"),
    ("AVR_SPDR",    0x4E, "SPI Data Register"),
    # Sleep
    ("AVR_SMCR",    0x53, "Sleep Mode Control Register"),
    # Reset/MCU status
    ("AVR_MCUSR",   0x54, "MCU Status Register (BORF/EXTRF/PORF/WDRF)"),
    # Watchdog
    ("AVR_WDTCSR",  0x60, "Watchdog Timer Control Register"),
    # Timer1 (16-bit)
    ("AVR_TIMSK1",  0x6F, "Timer/Counter1 Interrupt Mask Register"),
    ("AVR_ADCL",    0x78, "ADC Data Register Low"),
    ("AVR_ADCH",    0x79, "ADC Data Register High"),
    ("AVR_ADCSRA",  0x7A, "ADC Control and Status Register A"),
    ("AVR_ADCSRB",  0x7B, "ADC Control and Status Register B"),
    ("AVR_ADMUX",   0x7C, "ADC Multiplexer Selection Register"),
    # Timer1 control/data
    ("AVR_TCCR1A",  0x80, "Timer/Counter1 Control Register A"),
    ("AVR_TCCR1B",  0x81, "Timer/Counter1 Control Register B"),
    ("AVR_TCCR1C",  0x82, "Timer/Counter1 Control Register C"),
    # TCNT1 is 16-bit; low byte at 0x84, high at 0x85
    ("AVR_TCNT1L",  0x84, "Timer/Counter1 Low Byte"),
    ("AVR_TCNT1H",  0x85, "Timer/Counter1 High Byte"),
    ("AVR_ICR1L",   0x86, "Input Capture Register 1 Low"),
    ("AVR_ICR1H",   0x87, "Input Capture Register 1 High"),
    ("AVR_OCR1AL",  0x88, "Output Compare Register 1A Low"),
    ("AVR_OCR1AH",  0x89, "Output Compare Register 1A High"),
    ("AVR_OCR1BL",  0x8A, "Output Compare Register 1B Low"),
    ("AVR_OCR1BH",  0x8B, "Output Compare Register 1B High"),
    # UART0
    ("AVR_UCSR0A",  0xC0, "USART0 Control and Status Register A"),
    ("AVR_UCSR0B",  0xC1, "USART0 Control and Status Register B"),
    ("AVR_UCSR0C",  0xC2, "USART0 Control and Status Register C"),
    ("AVR_UBRR0L",  0xC4, "USART0 Baud Rate Register Low"),
    ("AVR_UBRR0H",  0xC5, "USART0 Baud Rate Register High"),
    ("AVR_UDR0",    0xC6, "USART0 I/O Data Register"),
    # TWI (I2C)
    ("AVR_TWBR",    0xB8, "TWI Bit Rate Register"),
    ("AVR_TWSR",    0xB9, "TWI Status Register"),
    ("AVR_TWAR",    0xBA, "TWI (Slave) Address Register"),
    ("AVR_TWDR",    0xBB, "TWI Data Register"),
    ("AVR_TWCR",    0xBC, "TWI Control Register"),
    ("AVR_TWAMR",   0xBD, "TWI (Slave) Address Mask Register"),
]

def compute_checksum(regs):
    data = b"".join(
        f"{name}={addr:02X}".encode()
        for name, addr, _ in sorted(regs, key=lambda r: r[1])
    )
    return zlib.crc32(data) & 0xFFFFFFFF

def generate_header(regs, checksum):
    lines = [
        "/*",
        " * RAF_avr_regs_generated.h — AUTO-GENERATED by scripts/gen_avr_regs.py",
        " * Source: ATmega328P datasheet Atmel 8271D, I/O Memory Map.",
        " * DO NOT EDIT MANUALLY — regenerate via: python3 scripts/gen_avr_regs.py",
        " *",
        f" * Checksum (CRC-32 of name=ADDR pairs sorted by address): 0x{checksum:08X}",
        " * Validate: python3 scripts/gen_avr_regs.py --check",
        " */",
        "",
        "#ifndef RAF_AVR_REGS_GENERATED_H",
        "#define RAF_AVR_REGS_GENERATED_H",
        "",
        "#include <stdint.h>",
        "",
        "/* Validation token — matches CRC-32 computed by gen_avr_regs.py */",
        f"#define RAF_AVR_REGS_CHECKSUM 0x{checksum:08X}UL",
        "",
        "/* All addresses are ATmega328P I/O memory map offsets (data space). */",
        "/* Access via RAFA_MMIO8(addr) macro from RAF_rafaelia_common.h.    */",
        "",
    ]
    for name, addr, desc in regs:
        lines.append(f"#define {name:<20} 0x{addr:02X}U  /* {desc} */")
    lines += [
        "",
        "#endif /* RAF_AVR_REGS_GENERATED_H */",
        "",
    ]
    return "\n".join(lines)

def validate_header(path, expected_checksum):
    """Re-parse the generated header and verify the embedded checksum matches."""
    import re
    regs = []
    try:
        with open(path) as f:
            for line in f:
                m = re.match(r"^#define\s+(AVR_\w+)\s+0x([0-9A-Fa-f]+)U\b", line)
                if m:
                    regs.append((m.group(1), int(m.group(2), 16), ""))
    except FileNotFoundError:
        print(f"ERROR: {path} not found", file=sys.stderr)
        return False
    actual = compute_checksum(regs)
    if actual != expected_checksum:
        print(f"CHECKSUM MISMATCH: expected 0x{expected_checksum:08X}, got 0x{actual:08X}", file=sys.stderr)
        return False
    print(f"OK: checksum 0x{actual:08X} verified ({len(regs)} registers)")
    return True

def main():
    import os
    checksum = compute_checksum(REGISTERS)
    header = generate_header(REGISTERS, checksum)

    if "--check" in sys.argv:
        out_path = os.path.join(os.path.dirname(__file__), "..", "RAF_avr_regs_generated.h")
        ok = validate_header(os.path.normpath(out_path), checksum)
        sys.exit(0 if ok else 1)

    print(header, end="")

if __name__ == "__main__":
    main()
